<div class="sitebar_list">
    <div class="sitebar_title">
        <h4>{{ $config['title'] }}</h4>
    </div>
    <div id="calendar">
        <script type="text/javascript">
            var calendar=function(a){a&&this.show()},cproto=calendar.prototype;cproto.toMonth=function(a,b){b=b||!1;var d="\u4e00\u6708 \u4e8c\u6708 \u4e09\u6708 \u56db\u6708 \u4e94\u6708 \u516d\u6708 \u4e03\u6708 \u516b\u6708 \u4e5d\u6708 \u5341\u6708 \u5341\u4e00\u6708 \u5341\u4e8c\u6708".split(" "),e="1\u6708 2\u6708 3\u6708 4\u6708 5\u6708 6\u6708 7\u6708 8\u6708 9\u6708 10\u6708 11\u6708 12\u6708".split(" ");return 0<=a&&11>=a?(a=parseInt(a,10),b?d[a]:e[a]):void 0};cproto.getNow=function(a){var b=new Date,d=b.getFullYear(),e=b.getMonth(),b=b.getDate();return a?{Y:d,m:e,d:b}:d.toString()+e};cproto.show=function(){var a=new Date,b=a.getFullYear(),a=a.getMonth();document.write(this.getMonthAllDate(b,a))};cproto.jump=function(a,b){a=parseInt(a,10);b=parseInt(b,10);var d=new Date(a,b,1);a=d.getFullYear();b=d.getMonth();document.getElementById("js_calendar").innerHTML=this.getMonthAllDate(a,b)};cproto.getMonthDate=function(a,b){a=parseInt(a,10);b=parseInt(b,10)+1;return(new Date(a,b,0)).getDate()};cproto.getMonthFirstDay=function(a,b){a=parseInt(a,10);b=parseInt(b,10);return(new Date(a,b,1)).getDay()};cproto.getMonthLastDay=function(a,b){a=parseInt(a,10);b=parseInt(b,10)+1;return(new Date(a,b,0)).getDay()};cproto.getMonthAllDate=function(a,b){a=parseInt(a,10);b=parseInt(b,10);for(var d=this.getMonthDate(a,b),e=this.getMonthDate(a,b-1),h=6,g=this.getMonthFirstDay(a,b),n=this.getMonthFirstDay(a,b),l=!1,f=0,c=a.toString()+b!==this.getNow()?'<span class="nowday"><a href="javascript:(new calendar).jump('+this.getNow(!0).Y+","+this.getNow(!0).m+')">\u4eca\u5929</a></span>':"",c='<div id="js_calendar"><table class="calendar">\r\n'+('<caption><span class="year"><a href="javascript:(new calendar).jump('+(a-1)+","+b+')"><<</a>'+a+'<a href="javascript:(new calendar).jump('+(a+1)+","+b+')">>></a></span>'+c+'<span class="day"><a href="javascript:(new calendar).jump('+a+","+(b-1)+')"><<</a>'+this.toMonth(b)+'<a href="javascript:(new calendar).jump('+a+","+(b+1)+')">>></a></span></caption>\r\n'),c=c+'<thead>\r\n<tr><td class="sun">\u65e5</td><td class="week">\u4e00</td><td class="week">\u4e8c</td><td class="week">\u4e09</td><td class="week">\u56db</td><td class="week">\u4e94</td><td class="week">\u516d</td></tr>\r\n',c=c+"</thead>\r\n",c=c+"<tbody>\r\n",k=0;6>k&&!(l||6==k&&6==n);k++){var c=c+"<tr>\r\n",m=0;for(f;h>=f;f++)g>f?c+='<td class="update">'+((e+=1)-g)+"</td>\r\n":6>=f?(r=f-g+1,c+=r==this.getNow(!0).d&&a.toString()+b==this.getNow()?'<td class="now">'+r+"</td>\r\n":"<td>"+r+"</td>\r\n"):(t=f-(g-1),t>d?(l=!0,c+='<td class="dodate">'+(m+=1)+"</td>\r\n"):c+=t==this.getNow(!0).d&&a.toString()+b==this.getNow()?'<td class="now">'+t+"</td>\r\n":"<td>"+t+"</td>\r\n");c+="</tr>\r\n";h+=7}return c+="</tbody>\r\n",c+"</table>\r\n</div>"};new calendar(!0);
        </script>
    </div>
</div>
